### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Fernando-A-Rocha** [Vadya963/vscode-mtalua#1]
Hello, I just found this repository. I noticed it's based on https://github.com/Subtixx/vscode-mtalua which seems a bit abandoned tbh. I also noticed you are a contributor on that repository and helped keep it updated.

My question is: are you going to keep that other repository updated or focus on this one? 🤔 @Vadya963

**Comment by Fernando-A-Rocha** [comment]
I installed this version by replacing files in 'subtixx.mtasa-lua-2.3.6', but wouldn't it be better if you made an actual release with a different version? XD

**Comment by Vadya963** [comment]
> I installed this version by replacing files in 'subtixx.mtasa-lua-2.3.6', but wouldn't it be better if you made an actual release with a different version? XD

if you download PR from the github from Subtixx, then there will only be syntax highlighting, and there will be no hints, so I created this PR for those who do not know how to properly install the extension from Subtixx. Sometimes I make pull requests in his github branch

**Comment by Fernando-A-Rocha** [comment]
@Vadya963 One year later i wanna tell you still use this extension which u updated 3 months ago.
I recommended it to other people. Thanks for ur work
